update paddle2onnx version & add yolov11 support

diff --git a/third_party/onnx/.azure-pipelines/Linux-CI.yml b/third_party/onnx/.azure-pipelines/Linux-CI.yml
--- a/third_party/onnx/.azure-pipelines/Linux-CI.yml
+++ b/third_party/onnx/.azure-pipelines/Linux-CI.yml
@@ -1,38 +1,54 @@
+# Copyright (c) ONNX Project Contributors
+#
+# SPDX-License-Identifier: Apache-2.0
+
+schedules:
+- cron: '0 0 * * *'
+  displayName: Nightly Linux CI in main branch
+  branches:
+    include:
+    - main
+
 trigger:
-- main
+- gh-readonly-queue/**
 
 jobs:
 - job: 'Test'
   pool:
-    vmImage: 'Ubuntu-18.04'
+    vmImage: 'Ubuntu-20.04'
   strategy:
     matrix:
-      py39-ml-debug:
+      py312-internal-protobuf:
+        python.version: '3.12'
+        onnx_ml: 1
+        build_type: 'Release'
+        documentation: 0
+        protobuf_type: 'Internal'
+      py311-ml-debug-external-protobuf:
+        python.version: '3.11'
+        onnx_ml: 1
+        build_type: 'Debug'
+        documentation: 0
+        protobuf_type: 'External'
+      py310-internal-protobuf:
+        python.version: '3.10'
+        onnx_ml: 0
+        build_type: 'Release'
+        documentation: 0
+        protobuf_type: 'Internal'
+      py39-ml-doc-external-protobuf:
         python.version: '3.9'
         onnx_ml: 1
-        onnx_debug: 1
-        onnx_lite: 0
-      py38:
+        build_type: 'Release'
+        documentation: 1
+        protobuf_type: 'External'
+      py38-internal-protobuf:
         python.version: '3.8'
         onnx_ml: 0
-        onnx_debug: 0
-        onnx_lite: 1
-      py38-ml:
-        python.version: '3.8'
-        onnx_ml: 1
-        onnx_debug: 0
-        onnx_lite: 1
-      py37:
-        python.version: '3.7'
-        onnx_ml: 0
-        onnx_debug: 0
-        onnx_lite: 1
-      py37-ml:
-        python.version: '3.7'
-        onnx_ml: 1
-        onnx_debug: 0
-        onnx_lite: 1
-    maxParallel: 6
+        build_type: 'Release'
+        documentation: 0
+        protobuf_type: 'Internal'
+    maxParallel: 4
 
   steps:
   - task: UsePythonVersion@0
@@ -42,67 +58,40 @@ jobs:
 
   - script: |
       python -m pip -q install virtualenv
-      python -m virtualenv py$(python.version)
-      source py$(python.version)/bin/activate
+      python -m virtualenv venv
+      source venv/bin/activate
 
-      source workflow_scripts/protobuf/build_protobuf_unix.sh $(nproc)
+      if [ '$(protobuf_type)' == 'External' ]; then
+        sudo apt-get install libprotobuf-dev protobuf-compiler
+      elif [ '$(protobuf_type)' == 'Internal' ]; then
+        echo "Use the internal protobuf build"
+      fi
 
-      python -m pip install -q --upgrade pip
-      python -m pip install -q -r requirements-release.txt
+      python -m pip install --upgrade pip
+      python -m pip install -r requirements-release.txt
+      # still test protobuf==3.20.2 at least in a CI
+      python -m pip install protobuf==3.20.2
 
       sudo apt-get install -qq -o=Dpkg::Use-Pty=0 -y --no-install-recommends dos2unix
+
       git submodule update --init --recursive
       export ONNX_BUILD_TESTS=1
-      if [ '$(onnx_debug)' == '1' ]; then
+      if [ '$(build_type)' == 'Debug' ]; then
         export DEBUG=1
       fi
       if [ '$(onnx_ml)' == '1' ]; then
         export ONNX_ML=1
       fi
-      export CMAKE_ARGS="-DONNXIFI_DUMMY_BACKEND=ON -DONNX_WERROR=ON"
-      if [ '$(onnx_lite)' == '1' ]; then
-        export CMAKE_ARGS="${CMAKE_ARGS} -DONNX_USE_LITE_PROTO=ON"
-      fi
-      export ONNX_NAMESPACE=ONNX_NAMESPACE_FOO_BAR_FOR_CI
-      python setup.py --quiet install
+      export CMAKE_ARGS="-DONNX_WERROR=ON -DONNX_USE_PROTOBUF_SHARED_LIBS=ON"
+      # Enable more sanitizers
+      export CMAKE_ARGS="${CMAKE_ARGS} -DCMAKE_CXX_FLAGS='-fsanitize=undefined -fno-sanitize-recover=all '"
+      pip install -e ".[reference]" -v
     displayName: 'Install ONNX and dependencies'
 
   - script: |
-      source py$(python.version)/bin/activate
+      source venv/bin/activate
 
-      # style check (flake8 and mypy)
-      pip install .[lint]
-      bash tools/style.sh
-      if [ $? -ne 0 ]; then
-        echo "style check failed"
-        exit 1
-      fi
-
-      # check line endings to be UNIX
-      find . -type f -regextype posix-extended -regex '.*\.(py|cpp|md|h|cc|proto|proto3|in)' | xargs dos2unix --quiet
-      git status
-      git diff --exit-code
-
-      # check auto-gen files up-to-date
-      python onnx/defs/gen_doc.py
-      python onnx/gen_proto.py -l
-      python onnx/gen_proto.py -l --ml
-      python onnx/backend/test/stat_coverage.py
-
-      git status
-      git diff --exit-code -- . ':(exclude)onnx/onnx-data.proto' ':(exclude)onnx/onnx-data.proto3'
-      if [ $? -ne 0 ]; then
-        echo "git diff returned failures"
-        exit 1
-      fi
-
-      # Do not hardcode onnx's namespace in the c++ source code, so that
-      # other libraries who statically link with onnx can hide onnx symbols
-      # in a private namespace.
-      ! grep -R --include='*.cc' --include='*.h' 'namespace onnx' .
-      ! grep -R --include='*.cc' --include='*.h' 'onnx::' .
-
-      pytest
+      pytest -sv --cov=onnx --cov-report=xml --cov-append --cov-branch --junit-xml pytest.xml -n auto --dist loadscope
       if [ $? -ne 0 ]; then
         echo "pytest failed"
         exit 1
@@ -116,25 +105,50 @@ jobs:
         exit 1
       fi
 
-      ./.setuptools-cmake-build/onnxifi_test_driver_gtests onnx/backend/test/data/node
-      if [ $? -ne 0 ]; then
-        echo "onnxifi_test_driver_gtests failed"
-        exit 1
-      fi
-
-      # Mypy only works with our generated _pb.py files when we install in develop mode, so let's do that
-      python -m pip uninstall -y onnx
-      rm -rf .setuptools-cmake-build
-      python -m pip install -q .
-
     displayName: 'Run ONNX tests'
 
   - script: |
-      source py$(python.version)/bin/activate
-      # onnx.checker all existing backend data
-      python workflow_scripts/test_generated_backend.py
-      # onnx.checker all generated backend data
-      python onnx/backend/test/cmd_tools.py generate-data
-      python workflow_scripts/test_generated_backend.py
+      curl -Os https://uploader.codecov.io/latest/linux/codecov
+      chmod +x codecov
+      ./codecov
+
+    continueOnError: true
+    displayName: 'Upload to codecov'
+
+  - script: |
+      source venv/bin/activate
+      python onnx/backend/test/cmd_tools.py generate-data --clean
+      git status
+      # Skip *output_*.pb because NumPy functions might behave differently on different platforms
+      # Skip test_log's input.pb because it uses np.random, which might behave differently on different platforms
+      git diff --exit-code -- . ':!onnx/onnx-data.proto' ':!onnx/onnx-data.proto3' ':!*output_*.pb' ':!*input_*.pb'
+      if [ $? -ne 0 ]; then
+        echo "git diff for test generation returned failures. Please check updated node test files"
+        exit 1
+      fi
+      git diff --exit-code --diff-filter=ADR -- . ':!onnx/onnx-data.proto' ':!onnx/onnx-data.proto3'
+      if [ $? -ne 0 ]; then
+        echo "Test generation returned failures. Please check the number of node test files (input_*.pb or output_*.pb)"
+        exit 1
+      fi
+
+      pip uninstall -y pillow
+      python onnx/backend/test/cmd_tools.py generate-data --clean
+      git status
+      # Verify test generation without pillow for ImageDecoder, it should directly use frozen data
+      git diff --exit-code -- . ':!onnx/onnx-data.proto' ':!onnx/onnx-data.proto3' ':!*output_*.pb' ':!*input_*.pb'
+      if [ $? -ne 0 ]; then
+        echo "git diff for test generation without pillow returned failures. Please check updated node test files"
+        exit 1
+      fi
 
     displayName: Test backend test data
+
+  - script: |
+      if [ '$(documentation)' == '1' ]; then
+        source venv/bin/activate
+        pip install -r docs/docsgen/source/requirements.txt
+        cd docs/docsgen && make text
+      fi
+    displayName: Test documentation
+    continueOnError: true  # the documentation generates errors due to operators documentation
